name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tagCreated: ${{ steps.create_tag.outputs.tagCreated }}
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Extract version from main.go
        id: extract_version
        run: |
          # Extraindo a versão a partir da constante definida em main.go
          VERSION=$(grep -oP 'const Version\s*=\s*"\K[^"]+' main.go)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Docker tag verification
        id: tag_verification
        run: |
          if docker manifest inspect $IMAGE:$TAG > /dev/null; then
            echo '::set-output name=tagCreated::true';
          else
            echo '::set-output name=tagCreated::false';
          fi
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/personalfinance
          TAG: ${{ steps.extract_version.outputs.version }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.tagCreated == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/personalfinance:v${{ needs.build.outputs.version }}
